laboratoriobridge/bold

.gitignore, src/components/elements/textual/HeadingSection/HeadingSection.test.tsx, src/components/elements/textual/HeadingSection/HeadingSection.tsx, src/components/elements/textual/HeadingSection/__snapshots__/HeadingSection.test.tsx.snap
Add vSpace prop to allow configuration of the spacing between Heading component and the children
=> [Heading Section] Add vSpace prop

src/components/MonthPicker/MonthPickerInput/MonthPickerInput.test.tsx, src/components/MonthPicker/MonthPickerInput/MonthPickerInput.tsx, src/components/MonthPicker/MonthPickerInput/__snapshots__/MonthPickerInput.test.tsx.snap
=> MonthPickerInput fix - issue #433

site/pages/components/text-field/TextField.demo.tsx, src/components/TextField/InputWrapper.tsx, src/components/TextField/TextField.stories.tsx, src/components/TextField/__snapshots__/InputWrapper.test.tsx.snap
=> Removing grey background from input icon when it is not a button

site/components/Tags.tsx, site/pages.ts, site/pages/components/overview/index.mdx, site/pages/components/overview/tags.tsx
Added new Component page (Overview)
=> New page Overview

src/components/Paginator/Paginator.test.tsx, src/components/Paginator/Paginator.tsx, src/components/Paginator/__snapshots__/Paginator.test.tsx.snap, src/components/Table/TableFooter/__snapshots__/TableFooter.test.tsx.snap
=> Correção do paginator

site/pages/components/table/DataTable.demo.tsx, site/pages/components/table/PagedTable.demo.tsx, src/components/Table/DataTable/DataTable.stories.tsx, src/components/Table/DataTable/DataTable.test.tsx, src/components/Table/DataTable/DataTable.tsx, src/components/Table/DataTable/TableFilledBody.tsx, src/components/Table/DataTable/__snapshots__/DataTable.test.tsx.snap, src/components/Table/PagedTable/__snapshots__/PagedTable.test.tsx.snap
closes https://github.com/laboratoriobridge/bold/issues/477
=> Add 'align' prop to TableColumnConfig

src/components/FileUploader/FileUploader.stories.tsx, src/components/FileUploader/FileUploader.tsx, src/components/FileUploader/__snapshots__/FileUploader.test.tsx.snap
=> alteração no visual do componente FileUploader

src/components/FileUploader/FileUploader.tsx, src/components/FileUploader/__snapshots__/FileUploader.test.tsx.snap
=> Fix border transparent - agora não samba

src/components/ButtonGroup/ButtonGroup.test.tsx, src/components/ButtonGroup/ButtonGroup.tsx, src/components/ButtonGroup/__snapshots__/ButtonGroup.test.tsx.snap, src/components/Dropdown/DropdownMenu.test.tsx, src/components/Dropdown/DropdownMenu.tsx, src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap, src/components/Dropdown/__snapshots__/DropdownMenu.test.tsx.snap, src/components/Tabs/Tabs.test.tsx, src/components/Tabs/Tabs.tsx, src/components/Tabs/__snapshots__/TabItem.test.tsx.snap, src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
=> Fix #511 - Options disabled are receiving focus at dropdowns

src/components/Calendar/Calendar.test.tsx, src/components/Calendar/Calendar.tsx, src/components/Calendar/MonthView.tsx, src/components/Calendar/__snapshots__/Calendar.test.tsx.snap, yarn.lock
https://github.com/laboratoriobridge/bold/issues/523
=> Performance improvements for Calendar and MonthView

src/components/Select/SelectMulti/SelectMulti.tsx
fixes https://github.com/laboratoriobridge/bold/issues/535
=> Fix multiple Select input focus handler

src/components/DateRangeField/DateRangeField.stories.tsx, src/components/DateRangeField/DateRangeField.test.tsx, src/components/DateRangeField/DateRangeField.tsx
=> [DateRangeField] fixing the behavior when receive an empty value

src/components/Select/SelectSingle/SelectSingle.test.tsx, src/components/Select/SelectSingle/SelectSingle.tsx
=> Focus Select input when clicking input icon

site/gatsby-node.js, site/package.json, site/yarn.lock, src/components/Tooltip/Tooltip.tsx, src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
=> #640 - Fix Popper in site error

src/components/MonthRangePicker/BaseMonthRangeInput.test.tsx, src/components/MonthRangePicker/MonthRangePicker.test.tsx, src/components/MonthRangePicker/MonthRangePicker.tsx, src/components/MonthRangePicker/RangeMonthCalendar/__snapshots__/ControlledMonthRangeCalendar.test.tsx.snap, src/components/MonthRangePicker/__snapshots__/MonthRangePicker.test.tsx.snap, src/components/MonthRangePicker/util.test.tsx, src/components/MonthRangePicker/util.tsx
Fixing the problem of not clearing the input value when clicking on the 'x' of the MonthRangePicker
=> Fixing the clear of MonthRangePicker

.github/workflows/yarn.yml, CONTRIBUTING.md, package.json
=> Updating the contributing, action and package.json to support node 14+

site/src/pages/components/dropdown/DropdownExample.demo.tsx
=> Fix and refactory DropdownExample to make site page works

.github/workflows/loki.yml, .github/workflows/publish-site.yml, .github/workflows/yarn.yml, package.json
vercel was dropped because of teams plan billing price, so I changed build action to check site builds.
also I added a new action to deploy bold's site
=> Change actions

src/components/Combobox/Combobox.stories.tsx, src/components/Combobox/ComboboxInline.test.tsx, src/components/Combobox/ComboboxInline.tsx, src/components/Combobox/ComboboxMultiselect.test.tsx, src/components/Combobox/ComboboxMultiselect.tsx, src/components/Combobox/ComboboxSingleselect.test.tsx, src/components/Combobox/ComboboxSingleselect.tsx, src/components/Combobox/__snapshots__/ComboboxInline.test.tsx.snap
=> #804 - Combobox/Select compatibility

src/components/FileUploader/FileUploader.tsx, src/components/FileUploader/__snapshots__/FileUploader.test.tsx.snap
=> Truncate the filename in the Fileuploader component
